(DEFUN MAKE-DR(NUM PHRASE)
  (LAMBDA (MSG)
   (IF (EQ MSG 'NUM)
       NUM
       (IF (EQ MSG 'PHRASE)
           PHRASE
           'UNKNOWN_MSG))))


(DEFINE TROUGHTON (MAKE-DR 2 'I-DONT-LIKE-IT))
(DEFINE PERTWEE (MAKE-DR 3 'REVERSE-THE-POLARITY))
(DEFINE BAKER (MAKE-DR 4 'JELLY-BABY))
(DEFINE ECCLESTON (MAKE-DR 9 'FANTASTIC))
(DEFINE TENNANT (MAKE-DR 10 'ALLONS-Y))
(DEFINE SMITH (MAKE-DR 11 'GERONIMO))
(DEFINE CAPALDI (MAKE-DR 12 '()))
